### ISSUE TITLE
Progress bar on download_file function doesn't seem to work on jupyter lab notebook

### ISSUE THREAD

**Issue by Munfred** [caltechlibrary/caltechdata_api#7]
The progress bar in the download_file function doesn't seem to work on jupyter lab notebook for me. See the screenshot below, it always showed 0% but the file was actually downloaded.

![image](https://user-images.githubusercontent.com/12504176/119604912-b9894780-bda4-11eb-91b7-e0b9f962976d.png)

**Comment by tmorrell** [comment]
Thanks for the report! I've switched out the progressbar approach, and v0.1.9 should work correctly in jupyter lab.
