### ISSUE TITLE
python >=3.7 required?

### ISSUE THREAD

**Issue by caseyjlaw** [caltechlibrary/caltechdata_api#9]
I am using python 3.6 and would like to easily install caltechdata_api. I noticed that I can clone and install from github. This seems to work in python 3.6 in my work.
Is Python >= 3.7 really required? If it wasn't, then I could use pypi to install this.

**Comment by tmorrell** [comment]
Nope, I just hadn't tested it on 3.6 until now. I've just made a new release that you should be able to install. Let me know if you run into any issues!

**Comment by caseyjlaw** [comment]
Thanks for the quick response.
